/**
 * Reads Supabase credentials from Vercel environment variables
 * and writes them into js/supabase.js before the site is served.
 *
 * Vercel-Supabase integration may set any of these (checked in order):
 *   SUPABASE_URL / NEXT_PUBLIC_SUPABASE_URL
 *   SUPABASE_ANON_KEY / NEXT_PUBLIC_SUPABASE_ANON_KEY
 */
const fs   = require('fs');
const path = require('path');

// Log all Supabase-related env vars present (without revealing values)
const sbVars = Object.keys(process.env).filter(k =>
  k.toUpperCase().includes('SUPABASE') || k.toUpperCase().includes('POSTGRES')
);
console.log('[inject-config] Supabase-related env vars found:', sbVars.length ? sbVars.join(', ') : '(none)');

// Known project URL — used as fallback if env var not set
const KNOWN_URL = 'https://yzpistceuhpcooyfgdvb.supabase.co';

const url  = process.env.SUPABASE_URL
          || process.env.NEXT_PUBLIC_SUPABASE_URL
          || KNOWN_URL;

const anon = process.env.SUPABASE_ANON_KEY
          || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY
          || '';

if (!anon) {
  console.warn('[inject-config] ⚠  SUPABASE_ANON_KEY not found in env vars.');
  console.warn('[inject-config]    The admin panel will show a configuration prompt.');
  console.warn('[inject-config]    Set SUPABASE_ANON_KEY in Vercel → Settings → Environment Variables.');
  // Don't abort — deploy without anon key; admin will prompt user to paste it.
} else {
  console.log('[inject-config] ✓ Credentials found — writing js/supabase.js');
}

const content = `import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

// Auto-generated by scripts/inject-config.js at build time.
// Do not edit — changes will be overwritten on next deployment.
export const SUPABASE_URL  = '${url}';
export const SUPABASE_ANON = '${anon}';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON, {
  auth: {
    persistSession:     false,
    autoRefreshToken:   false,
    detectSessionInUrl: false
  }
});
`;

const outPath = path.join(__dirname, '..', 'js', 'supabase.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('[inject-config] js/supabase.js written — URL:', url, '— Anon key:', anon ? '✓ present' : '✗ missing');
