/**
 * Reads Supabase credentials from Vercel environment variables
 * and writes them into js/supabase.js before the site is served.
 *
 * Vercel-Supabase integration sets:
 *   SUPABASE_URL          — project URL (https://xxxx.supabase.co)
 *   SUPABASE_ANON_KEY     — anon/public key (safe in browser JS)
 */
const fs   = require('fs');
const path = require('path');

const url  = process.env.SUPABASE_URL      || process.env.NEXT_PUBLIC_SUPABASE_URL  || '';
const anon = process.env.SUPABASE_ANON_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY || '';

if (!url || !anon) {
  console.warn('[inject-config] WARNING: SUPABASE_URL or SUPABASE_ANON_KEY env var not found.');
  console.warn('[inject-config] Public pages will fall back to data/projects.json.');
  console.warn('[inject-config] Admin login will not work until credentials are set.');
}

// persistSession: false — no tokens stored anywhere (localStorage or sessionStorage).
// Every page load requires a fresh login. This prevents auto-login bypass.
const content = `import { createClient } from 'https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm';

// Auto-generated by scripts/inject-config.js at build time
export const SUPABASE_URL  = '${url}';
export const SUPABASE_ANON = '${anon}';

export const supabase = createClient(SUPABASE_URL, SUPABASE_ANON, {
  auth: {
    persistSession: false,
    autoRefreshToken: false,
    detectSessionInUrl: false
  }
});
`;

const outPath = path.join(__dirname, '..', 'js', 'supabase.js');
fs.writeFileSync(outPath, content, 'utf8');
console.log('[inject-config] js/supabase.js written with Supabase credentials.');
